Sketch:
  "Dimensions":
    Dimension:
      #disabled: true
    angle:

  "Shapes":
    line:
    circle:
    #bezier:
    #  disabled: true
    #rectangle:
    #  disabled: true
    arc:
    #ellipse:
    #"rounded rectangle":
    #  disabled: true
    #bevel:
    #  disabled: true
    point:



