Sketch:
  "Dimension":
    Dimension:
      disabled: true
  "Add Entities":
    line:
    circle:
      disabled: true
    bezier:
      disabled: true
    rectangle:
      disabled: true
    arc:
    oval:
      disabled: true
    "rounded rectangle":
      disabled: true
    bevel:
      disabled: true
    point:
  "Modify Entities":
    "Trim Entities":
      disabled: true
    "Convert Entities":
      disabled: true
    "Offset Entities":
      disabled: true
    "Merge Entities":
      disabled: true
    "Linear Sketch Pattern":
      disabled: true
    "Move Entities":
      disabled: true
  "Sketch Options":
    "Display/Delete Relationship":
      disabled: true
    "Quick Snaps":
      disabled: true

